import Head from "next/head";
import Image from "next/image";
import Banner from "../components/Banner";
import styles from "../styles/Home.module.css";
import heroImage from "../public/static/hero-image.png";

export default function Home() {
  const handleOnClick = () => {
    console.log("banner button clicked");
  };
  return (
    <>
      <Head>
        <title>Coffee Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Banner
          buttonText={"View stores nearby"}
          handleOnClick={handleOnClick}
        />
        <div className={styles.heroImage}>
          <Image
            placeholder={"blur"}
            src={heroImage}
            width={700}
            height={400}
            alt={"hero image"}
          />
        </div>
      </main>
    </>
  );
}
